// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtdtTaDSXH_xTFdN3XM7BBtxYxw78T_is',
    appId: '1:749360667967:web:a2d9b497e8f53c1645478a',
    messagingSenderId: '749360667967',
    projectId: 'counceling-project2025',
    authDomain: 'counceling-project2025.firebaseapp.com',
    storageBucket: 'counceling-project2025.firebasestorage.app',
    measurementId: 'G-4052FMN6R7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6BuOj0Snlg--7NEU2a8doFXqaoyjkiy8',
    appId: '1:749360667967:android:ad40d054cf1e8f7245478a',
    messagingSenderId: '749360667967',
    projectId: 'counceling-project2025',
    storageBucket: 'counceling-project2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIignTpsBibewOIijETDz4WOrYhj4gEKI',
    appId: '1:749360667967:ios:2956b5ef2a7d285845478a',
    messagingSenderId: '749360667967',
    projectId: 'counceling-project2025',
    storageBucket: 'counceling-project2025.firebasestorage.app',
    iosClientId: '749360667967-fsm8ihsuntoab6u1lrr47dkqonqo8udt.apps.googleusercontent.com',
    iosBundleId: 'com.example.termProject2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIignTpsBibewOIijETDz4WOrYhj4gEKI',
    appId: '1:749360667967:ios:2956b5ef2a7d285845478a',
    messagingSenderId: '749360667967',
    projectId: 'counceling-project2025',
    storageBucket: 'counceling-project2025.firebasestorage.app',
    iosClientId: '749360667967-fsm8ihsuntoab6u1lrr47dkqonqo8udt.apps.googleusercontent.com',
    iosBundleId: 'com.example.termProject2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtdtTaDSXH_xTFdN3XM7BBtxYxw78T_is',
    appId: '1:749360667967:web:c0395edf4301a81545478a',
    messagingSenderId: '749360667967',
    projectId: 'counceling-project2025',
    authDomain: 'counceling-project2025.firebaseapp.com',
    storageBucket: 'counceling-project2025.firebasestorage.app',
    measurementId: 'G-EBP9D44WQ3',
  );
}
